#!/bin/sh

set -e

USERNAME="${USERNAME:-"automatic"}"

if [ "$(id -u)" -ne 0 ]; then
    echo -e 'Script must be run as root. Use sudo, su, or add "USER root" to your Dockerfile before running this script.'
    exit 1
fi

mkdir -p /home/"$USERNAME"/.local/bin
ln -s /usr/bin/fdfind /home/"$USERNAME"/.local/bin/fd

{
    echo "## start: generated by post setup feature"
    echo "source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
    echo "source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
    echo "plugins+=(fd rg fzf mvn gradle)"
    echo "## end"
} >> /home/"$USERNAME"/.zshrc

exit 0
