#!/bin/sh

set -e

USERNAME="${USERNAME:-"automatic"}"

if [ "$(id -u)" -ne 0 ]; then
    echo -e 'Script must be run as root. Use sudo, su, or add "USER root" to your Dockerfile before running this script.'
    exit 1
fi

{
    echo "## start: generated by post setup feature"
    echo "source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
    echo "source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
    echo "source /usr/share/doc/fzf/examples/key-bindings.zsh"
    echo "## end"
} >> /home/"$USERNAME"/.zshrc

exit 0
