name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GERG_REGISTRY_TOKEN }}

      - name: Build jdk17-quarto
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/jdk17-quarto
          imageName: ghcr.io/gvdenbro/jdk17-quarto

      - name: Build jupyte-r
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/jupyte-r
          imageName: ghcr.io/gvdenbro/jupyte-r
  