name: 'scheduled no cache build' 
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * SUN"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GERG_REGISTRY_TOKEN }}

      - name: Build jdk17-quarto
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/jdk17-quarto
          noCache: true
          imageName: ghcr.io/gvdenbro/jdk17-quarto

      - name: Build jupyte-r
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src/jupyte-r
          noCache: true
          imageName: ghcr.io/gvdenbro/jupyte-r
